version: "3"
services:
  redis:
    image: redis
    command: redis-server
    volumes:
      - ./deployment/redis:/data
    ports:
      - "6379:6379"
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: gwjrl
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./deployment/postgresql/data:/var/lib/posqtgresql/data
    ports:
      - "5433:5432"
    restart: always

  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:flask_app
      - /tmp/log:/tmp
    command: bash start.sh
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ./migrations:/usr/src/app/migrations
    restart: always
  nginx:
    build: deployment/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8000"
    volumes:
      - ./collect_static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./deployment/nginx/ssl:/usr/share/nginx/ssl
    links:
      - web
    depends_on:
      - web
    restart: always

